
server:
#  port: 8085
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: "adrian10jet"
    url: "jdbc:mysql://mysql-koltrum.alwaysdata.net/koltrum_db?reconnect=true"
    username: "koltrum"
#    password:
#    url: "jdbc:mysql://localhost:3306/koltrum_db?reconnect=true"
#    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false